# Site settings
title: "Malte Mittendorf Curriculum Vitae"
description: "https://mamittendorf.github.io/resume/"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Malte Mittendorf"
resume_title:                   "PhD student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "malte.mittendorf@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
#display_header_contact_info:    "false"

resume_header_intro: "<p>Currently, I am working as a PhD student at the Section of Fluid Mechanics and Coastal and Maritime Engineering (DTU MEK) and my project is about the combination of the governing physics and statistics of ships in a seaway with machine learning models. I have a strong background in ship hydrodynamics and design. During my time at HSVA I had the opportunity to participate in two EU research projects: HOLISHIP & TrAM. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
#resume_section_projects:        true
resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mamittendorf"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://de.linkedin.com/in/malte-mittendorf-1a046b195"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://www.researchgate.net/profile/Malte-Mittendorf"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
